"""Pydantic schemas for API request/response models."""

from devograph.schemas.developer import (
    DeveloperCreate,
    DeveloperResponse,
    DeveloperUpdate,
    SkillFingerprint,
)
from devograph.schemas.auth import GitHubAuthResponse, TokenResponse
from devograph.schemas.career import (
    CareerRoleCreate,
    CareerRoleResponse,
    CareerRoleUpdate,
    RoleRequirements,
    RoleGapAnalysis,
    RoleSuggestion,
    PromotionReadiness,
    LearningPathCreate,
    LearningPathGenerate,
    LearningPathResponse,
    LearningMilestoneResponse,
    PathProgressUpdate,
    StretchAssignment,
    TeamGapAnalysis,
    BusFactorRisk,
    RoadmapSkillAnalysis,
    GeneratedJD,
    InterviewRubric,
    HiringRequirementCreate,
    HiringRequirementResponse,
    CandidateScorecard,
    OrganizationSettingsCreate,
    OrganizationSettingsResponse,
    OrganizationSettingsUpdate,
)
from devograph.schemas.analytics import (
    # Enums
    WidgetType,
    MetricType,
    ScheduleFrequency,
    DeliveryMethod,
    ExportFormat,
    ExportType,
    ExportStatus,
    InsightType,
    RiskLevel,
    Trajectory,
    HealthGrade,
    # Report schemas
    WidgetConfig,
    ReportFilters,
    CustomReportCreate,
    CustomReportUpdate,
    CustomReportResponse,
    ReportTemplateResponse,
    ScheduledReportCreate,
    ScheduledReportUpdate,
    ScheduledReportResponse,
    # Export schemas
    ExportRequest,
    ExportJobResponse,
    # Analytics data schemas
    DateRange,
    SkillHeatmapData,
    ActivityHeatmapData,
    ProductivityTrends,
    WorkloadDistribution,
    CollaborationGraph,
    # Predictive schemas
    AttritionRiskAnalysis,
    BurnoutRiskAssessment,
    PerformanceTrajectory,
    TeamHealthAnalysis,
    PredictiveInsightResponse,
    # Request schemas
    SkillHeatmapRequest,
    ProductivityRequest,
    WorkloadRequest,
    CollaborationRequest,
    TeamHealthRequest,
)
from devograph.schemas.integrations import (
    SlackNotificationType,
    SlackCommandType,
    SlackOAuthCallback,
    SlackIntegrationResponse,
    SlackIntegrationUpdate,
    SlackMessage,
    SlackNotificationRequest,
    SlackNotificationResponse,
    SlackSlashCommand,
    SlackCommandResponse,
    SlackInteraction,
    SlackEvent,
    SlackUserMappingRequest,
    SlackUserMappingResponse,
    SlackNotificationLogResponse,
)

__all__ = [
    # Developer schemas
    "DeveloperCreate",
    "DeveloperResponse",
    "DeveloperUpdate",
    "SkillFingerprint",
    # Auth schemas
    "GitHubAuthResponse",
    "TokenResponse",
    # Career schemas
    "CareerRoleCreate",
    "CareerRoleResponse",
    "CareerRoleUpdate",
    "RoleRequirements",
    "RoleGapAnalysis",
    "RoleSuggestion",
    "PromotionReadiness",
    "LearningPathCreate",
    "LearningPathGenerate",
    "LearningPathResponse",
    "LearningMilestoneResponse",
    "PathProgressUpdate",
    "StretchAssignment",
    "TeamGapAnalysis",
    "BusFactorRisk",
    "RoadmapSkillAnalysis",
    "GeneratedJD",
    "InterviewRubric",
    "HiringRequirementCreate",
    "HiringRequirementResponse",
    "CandidateScorecard",
    "OrganizationSettingsCreate",
    "OrganizationSettingsResponse",
    "OrganizationSettingsUpdate",
    # Analytics schemas (Phase 4)
    "WidgetType",
    "MetricType",
    "ScheduleFrequency",
    "DeliveryMethod",
    "ExportFormat",
    "ExportType",
    "ExportStatus",
    "InsightType",
    "RiskLevel",
    "Trajectory",
    "HealthGrade",
    "WidgetConfig",
    "ReportFilters",
    "CustomReportCreate",
    "CustomReportUpdate",
    "CustomReportResponse",
    "ReportTemplateResponse",
    "ScheduledReportCreate",
    "ScheduledReportUpdate",
    "ScheduledReportResponse",
    "ExportRequest",
    "ExportJobResponse",
    "DateRange",
    "SkillHeatmapData",
    "ActivityHeatmapData",
    "ProductivityTrends",
    "WorkloadDistribution",
    "CollaborationGraph",
    "AttritionRiskAnalysis",
    "BurnoutRiskAssessment",
    "PerformanceTrajectory",
    "TeamHealthAnalysis",
    "PredictiveInsightResponse",
    "SkillHeatmapRequest",
    "ProductivityRequest",
    "WorkloadRequest",
    "CollaborationRequest",
    "TeamHealthRequest",
    # Integration schemas (Phase 4)
    "SlackNotificationType",
    "SlackCommandType",
    "SlackOAuthCallback",
    "SlackIntegrationResponse",
    "SlackIntegrationUpdate",
    "SlackMessage",
    "SlackNotificationRequest",
    "SlackNotificationResponse",
    "SlackSlashCommand",
    "SlackCommandResponse",
    "SlackInteraction",
    "SlackEvent",
    "SlackUserMappingRequest",
    "SlackUserMappingResponse",
    "SlackNotificationLogResponse",
]
