-- Migration: drop `document_notifications`, now that everything it carried is
-- delivered through NotificationService.
--
-- Documents had a second, parallel notification system: this table, a
-- `GET /documents/notifications` endpoint with mark-read routes, a
-- `useDocumentNotifications` hook, and an "Inbox" entry in the docs sidebar
-- opening its own panel.
--
-- One thing actually wrote to it: `proposed_edits_service` inserted an
-- `ai_proposal` row when an AI proposed an edit, telling the document owner a
-- review was pending. That was the whole problem. Because the row lived here
-- rather than in `notifications`, it got no email, no per-user channel
-- preference, and no place in the main notification bell — so a proposal
-- generated by a scheduled sync, which nobody clicked anything to cause, waited
-- for the owner to happen to open one specific panel.
--
-- That path now emits the `document_ai_proposal` event through
-- NotificationService, alongside `document_shared`, `document_commented` and
-- `document_mentioned`. One inbox, one set of preferences, email included.
--
-- Existing rows are not migrated. They are "an AI proposed an edit, go and look"
-- pointers whose proposals are still sitting in `document_proposed_edits` and
-- still visible on the document; backfilling stale notifications into the main
-- bell would page people about weeks-old proposals the moment this ships.

BEGIN;

DROP INDEX IF EXISTS ix_document_notifications_developer_unread;
DROP INDEX IF EXISTS ix_document_notifications_developer_id;
DROP INDEX IF EXISTS ix_document_notifications_document_id;

DROP TABLE IF EXISTS document_notifications;

COMMIT;
