#!/usr/bin/env node

/**
 * Rewrite the tool-catalogue table inside docs/mcp.md from the generated MCP
 * manifest, so the prose is hand-written and the table never is.
 *
 * Replaces everything between the BEGIN/END markers; touches nothing else.
 * Runs at prebuild BEFORE generate-docs.mjs, which copies docs/ into
 * public/docs/ — order matters or the published copy lags a build behind.
 *
 *   node scripts/generate-mcp-doc.mjs
 *   node scripts/generate-mcp-doc.mjs --check   # CI: fail if the table is stale
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const DOC = path.resolve(ROOT, "..", "docs", "mcp.md");
const MANIFEST = path.join(ROOT, "src", "config", "mcpTools.generated.json");

const BEGIN = "<!-- BEGIN GENERATED TOOLS -->";
const END = "<!-- END GENERATED TOOLS -->";

if (!fs.existsSync(DOC)) {
  console.warn("  docs/mcp.md not found — skipping MCP doc generation");
  process.exit(0);
}

const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));

const lines = [
  BEGIN,
  "",
  `<!-- Generated by frontend/scripts/generate-mcp-doc.mjs from aexy-mcp ${manifest.server_version}. Do not edit by hand. -->`,
  "",
];

for (const category of manifest.categories) {
  lines.push(`### ${category.name}`);
  lines.push("");
  lines.push(`Capability: \`${category.capability}\``);
  lines.push("");
  lines.push("| Tool | Writes | Description |");
  lines.push("| --- | --- | --- |");
  for (const tool of category.tools) {
    const description = tool.description.replace(/\|/g, "\\|");
    lines.push(`| \`${tool.name}\` | ${tool.mutating ? "yes" : "no"} | ${description} |`);
  }
  lines.push("");
}

const total = manifest.categories.reduce((n, c) => n + c.tools.length, 0);
lines.push(
  `${total} tools across ${manifest.categories.length} categories, from \`aexy-mcp\` ${manifest.server_version}.`
);
lines.push("");
lines.push(END);

const doc = fs.readFileSync(DOC, "utf8");
const start = doc.indexOf(BEGIN);
const finish = doc.indexOf(END);
if (start === -1 || finish === -1) {
  console.error(`✗ docs/mcp.md is missing the ${BEGIN} / ${END} markers`);
  process.exit(1);
}

const next = doc.slice(0, start) + lines.join("\n") + doc.slice(finish + END.length);

if (process.argv.includes("--check")) {
  if (next !== doc) {
    console.error("✗ docs/mcp.md tool table is stale. Run: npm run mcp:doc");
    process.exit(1);
  }
  console.log(`✓ docs/mcp.md tool table current (${total} tools)`);
  process.exit(0);
}

if (next !== doc) {
  fs.writeFileSync(DOC, next);
  console.log(`  Regenerated docs/mcp.md tool table (${total} tools)`);
} else {
  console.log(`  docs/mcp.md tool table already current (${total} tools)`);
}
